import "@/styles/globals.css";
import type { Metadata } from "next";
import { Header, Navbar, Main } from "@labs/ui";

export const metadata: Metadata = {
  title: "Labs Company",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header>
          <Navbar>
            <h1>Hola</h1>
          </Navbar>
        </Header>
        <Main>{children}</Main>
      </body>
    </html>
  );
}
